// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Arc {
    "aid": number;
    "videos": number;
    "type_id": number;
    "type_name": string;
    "copyright": number;
    "pic": string;
    "title": string;
    "pubdate": number;
    "ctime": number;
    "desc": string;
    "state": number;
    "duration": number;
    "rights": ArcRights;
    "author": VideoOwner;
    "stat": VideoStat;
    "dynamic": string;
    "dimension": Dimension;
    "desc_v2": any;
    "is_chargeable_season": boolean;
    "is_blooper": boolean;
    "enable_vt": number;
    "vt_display": string;
    "type_id_v2": number;
    "type_name_v2": string;
    "is_lesson_video": number;
}

export interface ArcRights {
    "bp": number;
    "elec": number;
    "download": number;
    "movie": number;
    "pay": number;
    "hd5": number;
    "no_reprint": number;
    "autoplay": number;
    "ugc_pay": number;
    "is_cooperation": number;
    "ugc_pay_preview": number;
    "arc_pay": number;
    "free_watch": number;
}

/**
 * AudioItem DASH 音频流项
 */
export interface AudioItem {
    /**
     * 音频流 ID（与音质对应）
     */
    "id": number;

    /**
     * 主播放地址（驼峰命名）
     */
    "baseUrl": string;

    /**
     * 主播放地址（下划线命名）
     */
    "base_url": string;

    /**
     * 备用播放地址列表（驼峰命名）
     */
    "backupUrl": string[] | null;

    /**
     * 备用播放地址列表（下划线命名）
     */
    "backup_url": string[] | null;

    /**
     * 码率，单位 bps
     */
    "bandwidth": number;

    /**
     * MIME 类型（驼峰命名）
     */
    "mimeType": string;

    /**
     * MIME 类型（下划线命名）
     */
    "mime_type": string;

    /**
     * 编码格式（如 "mp4a.40.2"）
     */
    "codecs": string;

    /**
     * 宽度（音频通常为 0）
     */
    "width": number;

    /**
     * 高度（音频通常为 0）
     */
    "height": number;

    /**
     * 帧率（音频通常为空）
     */
    "frameRate": string;

    /**
     * 帧率（音频通常为空）
     */
    "frame_rate": string;

    /**
     * 像素宽高比（音频通常为空）
     */
    "sar": string;

    /**
     * SAP 类型（驼峰命名）
     */
    "startWithSap": number;

    /**
     * SAP 类型（下划线命名）
     */
    "start_with_sap": number;

    /**
     * 分段信息（驼峰命名）
     */
    "SegmentBase": SegmentBase;

    /**
     * 分段信息（下划线命名）
     */
    "segment_base": SegmentBase1;

    /**
     * 音频编码器 ID
     */
    "codecid": number;
}

/**
 * AutoQnResp 自动清晰度响应
 */
export interface AutoQnResp {
    /**
     * 染色ID，用于追踪
     */
    "dyeid": string;
}

/**
 * CollectionData 合集列表元信息
 */
export interface CollectionData {
    "count": number;
    "list": CollectionDataList[] | null;
    "has_more": boolean;
}

export interface CollectionDataList {
    "id": number;
    "fid": number;
    "mid": number;
    "attr": number;
    "attr_desc": string;
    "title": string;
    "cover": string;
    "upper": CollectionUpper;
    "cover_type": number;
    "intro": string;
    "ctime": number;
    "mtime": number;
    "state": number;
    "fav_state": number;
    "media_count": number;
    "view_count": number;
    "vt": number;
    "is_top": boolean;
    "recent_fav": any;
    "play_switch": number;
    "type": number;
    "link": string;
    "bvid": string;
}

export interface CollectionItemCntInfo {
    "collect": number;
    "play": number;
    "danmaku": number;
    "vt": number;
}

/**
 * CollectionItemData 合集元信息
 */
export interface CollectionItemData {
    "info": CollectionItemInfo;
    "medias": CollectionItemMedias[] | null;
}

export interface CollectionItemInfo {
    "id": number;
    "season_type": number;
    "title": string;
    "cover": string;
    "upper": CollectionItemUpper;
    "cnt_info": CollectionItemCntInfo;
    "media_count": number;
    "intro": string;
    "enable_vt": number;
}

export interface CollectionItemMediaCntInfo {
    "collect": number;
    "play": number;
    "danmaku": number;
    "vt": number;
}

export interface CollectionItemMediaUpper {
    "mid": number;
    "name": string;
}

export interface CollectionItemMedias {
    "id": number;
    "title": string;
    "cover": string;
    "duration": number;
    "pubtime": number;
    "bvid": string;
    "upper": CollectionItemMediaUpper;
    "cnt_info": CollectionItemMediaCntInfo;
    "enable_vt": number;
    "vt_display": string;
    "is_self_view": boolean;
}

export interface CollectionItemUpper {
    "mid": number;
    "name": string;
}

export interface CollectionUpper {
    "mid": number;
    "name": string;
    "face": string;
    "jump_link": string;
}

export interface CookieRefreshData {
    "status": number;
    "message": string;
    "refresh_token": string;
    "refresh": boolean;
}

/**
 * Dash 流信息（Dynamic Adaptive Streaming over HTTP，音视频分离）
 */
export interface Dash {
    /**
     * 视频总时长，单位秒
     */
    "duration": number;

    /**
     * 最小缓冲时间（驼峰命名）
     */
    "minBufferTime": number;

    /**
     * 最小缓冲时间（下划线命名）
     */
    "min_buffer_time": number;

    /**
     * 视频流列表（不同清晰度）
     */
    "video": VideoItem[] | null;

    /**
     * 音频流列表（不同音质）
     */
    "audio": AudioItem[] | null;

    /**
     * 杜比音效信息
     */
    "dolby": Dolby;

    /**
     * Hi-Res 无损音轨信息（为 null 时表示不支持）
     */
    "flac": Flac | null;
}

export interface Dimension {
    "width": number;
    "height": number;
    "rotate": number;
}

/**
 * Dolby 杜比音效信息
 */
export interface Dolby {
    /**
     * 杜比类型：1=杜比全景声, 2=杜比视界
     */
    "type": number;

    /**
     * 杜比音频流列表（通常为数组或 null）
     */
    "audio": any;
}

/**
 * DownloadHistoryItem 下载历史记录
 */
export interface DownloadHistoryItem {
    "bvid": string;
    "cid": number;
    "title": string;
    "cover": string;
    "duration": number;
    "upperName": string;
    "play": number;
    "danmaku": number;
    "pubtime": number;
    "sourceName": string;
    "sourceKind": string;
    "path": string;
    "downloadKind": string;

    /**
     * Wails 绑定生成不支持直接暴露 time.Time，保存为 RFC3339 字符串给前端解析。
     */
    "downloaded": string;
}

/**
 * DynamicArchiveItem is the flattened video payload used by downstream download flows.
 */
export interface DynamicArchiveItem {
    "bvid": string;
    "title": string;
    "cover": string;
    "duration_text": string;
    "author_name": string;
    "pub_time": string;
    "pub_ts": number;
}

/**
 * DynamicArchivePage is a Wails-friendly single return value for one dynamic page.
 */
export interface DynamicArchivePage {
    "items": DynamicArchiveItem[] | null;
    "offset": string;
    "has_more": boolean;
}

export interface Episode {
    "season_id": number;
    "section_id": number;
    "id": number;
    "aid": number;
    "cid": number;
    "title": string;
    "attribute": number;
    "arc": Arc;
    "page": UgcSeasonPageItem;
    "bvid": string;
    "pages": UgcSeasonPageItem[] | null;
}

export interface EpisodicButton {
    "text": string;
    "uri": string;
}

/**
 * FavoriteData 收藏夹详情，包含了收藏夹内的视频列表等信息
 */
export interface FavoriteData {
    "info": FavoriteInfo;
    "medias": FavoriteMedias[] | null;
    "has_more": boolean;
    "ttl": number;
}

/**
 * FavoriteInfo 收藏夹元数据
 */
export interface FavoriteInfo {
    /**
     * 收藏夹mlid（完整id）	收藏夹原始id+创建者mid尾号2位
     */
    "id": number;

    /**
     * 收藏夹原始id
     */
    "fid": number;

    /**
     * 创建者mid
     */
    "mid": number;

    /**
     * 0：正常，1： 失效
     */
    "attr": number;

    /**
     * 收藏夹名称，如果失效会显示：已失效视频
     */
    "title": string;

    /**
     * 封面图片
     */
    "cover": string;

    /**
     * 收藏夹用户信息
     */
    "upper": FavoriteInfoUpper;
    "cover_type": number;

    /**
     * 收藏夹状态数
     */
    "cnt_info": FavoriteInfoCntInfo;
    "type": number;

    /**
     * 备注
     */
    "intro": string;

    /**
     * 创建时间
     */
    "ctime": number;

    /**
     * 收藏时间
     */
    "mtime": number;
    "state": number;
    "fav_state": number;
    "like_state": number;

    /**
     * 内容数量
     */
    "media_count": number;
    "is_top": boolean;
}

export interface FavoriteInfoCntInfo {
    /**
     * 收藏数
     */
    "collect": number;

    /**
     * 播放数
     */
    "play": number;

    /**
     * 点赞数
     */
    "thumb_up": number;

    /**
     * 分享数
     */
    "share": number;
}

/**
 * FavoriteInfoUpper info中的用户信息
 */
export interface FavoriteInfoUpper {
    "mid": number;
    "name": string;
    "face": string;
    "followed": boolean;
    "vip_type": number;
    "vip_statue": number;
}

export interface FavoriteItem {
    "id": number;
    "fid": number;
    "mid": number;
    "attr": number;
    "title": string;
    "fav_state": number;
    "media_count": number;
}

export interface FavoriteMediaCntInfo {
    /**
     * 收藏数
     */
    "collect": number;

    /**
     * 播放数
     */
    "play": number;

    /**
     * 弹幕数
     */
    "danmaku": number;
    "vt": number;
    "play_switch": number;
    "reply": number;

    /**
     * 播放数文本, 比如：12.3万
     */
    "view_text_1": string;
}

export interface FavoriteMediaUgc {
    "first_cid": number;
}

export interface FavoriteMediaUpper {
    "mid": number;
    "name": string;
    "face": string;
    "jump_link": string;
}

/**
 * FavoriteMedias 收藏夹内的视频信息，包含了视频的基本信息和一些状态信息
 */
export interface FavoriteMedias {
    /**
     * 内容id，视频稿件：视频稿件avid ; 音频：音频auid ;视频合集：视频合集id
     */
    "id": number;

    /**
     * 内容类型， 2：视频稿件； 12：音频；21：视频合集
     */
    "type": number;

    /**
     * 标题
     */
    "title": string;

    /**
     * 封面url
     */
    "cover": string;

    /**
     * 简介
     */
    "intro": string;

    /**
     * 视频分P数
     */
    "page": number;

    /**
     * 视频/音频时长
     */
    "duration": number;

    /**
     * up主信息
     */
    "upper": FavoriteMediaUpper;

    /**
     * 0: 正常; 9: up自己删除；1： 其他原因删除
     */
    "attr": number;

    /**
     * 状态数
     */
    "cnt_info": FavoriteMediaCntInfo;

    /**
     * 跳转uri，bilibili://video/xxxxx
     */
    "link": string;

    /**
     * 创建时间
     */
    "ctime": number;

    /**
     * 发布时间
     */
    "pubtime": number;

    /**
     * 收藏时间
     */
    "fav_time": number;

    /**
     * 视频稿件bvid
     */
    "bv_id": string;

    /**
     * 视频稿件bvid
     */
    "bvid": string;
    "season": any;
    "ogv": any;
    "ugc": FavoriteMediaUgc;

    /**
     * bilibili://music/playlist/playpage/3997344669?page_type=3\u0026oid=1305850968\u0026otype=2
     */
    "media_list_link": string;
}

/**
 * FavoritesData 收藏夹列表，包含了用户的所有收藏夹信息，但不包含收藏夹内的视频列表等详细信息
 */
export interface FavoritesData {
    "count": number;
    "list": FavoriteItem[] | null;
    "season": any;
}

/**
 * Flac Hi-Res 无损音频信息
 */
export interface Flac {
    /**
     * 是否在播放器显示切换 Hi-Res 无损音轨按钮
     */
    "display": boolean;

    /**
     * 无损音频流信息
     */
    "audio": AudioItem;
}

/**
 * FollowData 关注列表， 只记录部分重要字段
 */
export interface FollowData {
    "list": FollowDataList[] | null;

    /**
     * 未知
     */
    "re_version": number;

    /**
     * 自己关注了多少人
     */
    "total": number;
}

export interface FollowDataList {
    /**
     * 关注的用户的mid
     */
    "mid": number;

    /**
     * 对方对于自己的关系属性. 0： 未关注， 2： 已关注, 6: 互粉, 128: 已拉黑
     */
    "attribute": number;

    /**
     * 关注时间
     */
    "mtime": number;
    "tag": any;
    "special": number;

    /**
     * 用户昵称
     */
    "uname": string;

    /**
     * 用户头像url
     */
    "face": string;

    /**
     * 用户签名
     */
    "sign": string;
}

export interface LogOut {
    /**
     * 0：成功，2202：csrf请求非法
     */
    "code": number;
    "status": boolean;

    /**
     * 时间戳
     */
    "ts": number;
    "data": LogOutData;
}

export interface LogOutData {
    /**
     * 退出登录后跳转的URL
     */
    "redirectUrl": string;
}

export interface MyInfoExpertInfo {
    "title": string;
    "state": number;
    "type": number;
    "desc": string;
}

export interface MyInfoNamePlate {
    /**
     * 勋章id
     */
    "nid": number;

    /**
     * 勋章名称
     */
    "name": string;

    /**
     * 挂件图片url
     */
    "image": string;

    /**
     * 挂件图片url (小图)
     */
    "image_small": string;

    /**
     * 勋章等级
     */
    "level": string;

    /**
     * 勋章条件
     */
    "condition": string;
}

export interface MyInfoOfficial {
    /**
     * 认证类型
     */
    "role": number;

    /**
     * 认证信息
     */
    "title": string;

    /**
     * 认证备注
     */
    "desc": string;

    /**
     * 是否认证，-1：未认证，0：个人认证
     */
    "type": number;
}

export interface MyInfoProfession {
    "id": number;
    "name": string;
    "is_show": number;
    "category_one": string;
    "realname": string;
    "title": string;
    "department": string;
    "certificate_no": string;
    "certificate_show": boolean;
}

export interface MyInfoProfile {
    "mid": number;
    "name": string;
    "sex": string;

    /**
     * Face 头像链接
     */
    "face": string;

    /**
     * 个性签名
     */
    "sign": string;
    "rank": number;

    /**
     * 等级
     */
    "level": number;
    "birthday": number;

    /**
     * 应该没用，目前是0
     */
    "jointime": number;

    /**
     * 节操
     */
    "moral": number;

    /**
     * 封禁状态， 0：未封禁， 1：封禁
     */
    "silence": number;

    /**
     * 邮箱状态， 0：未绑定， 1：绑定
     */
    "email_status": number;

    /**
     * 手机状态， 0：未绑定， 1：绑定
     */
    "tel_status": number;

    /**
     * 作用不明确
     */
    "identification": number;
    "is_fake_account": number;
    "is_tourist": number;

    /**
     * 作用不明确
     */
    "pin_prompting": number;
    "official": MyInfoOfficial;
    "nameplate": MyInfoNamePlate;
    "vip": UserVip;

    /**
     * 是否是风纪委用户
     */
    "is_rip_user": boolean;
    "is_reg_audit": number;
    "country_code": string;
    "expert_info": MyInfoExpertInfo;
    "profession": MyInfoProfession;
}

export interface MyInfoVipLabel {
    "path": string;
    "text": string;
    "label_theme": string;
    "text_color": string;
    "bg_color": string;
    "border_color": string;
    "img_label_uri_hant_static": string;
    "img_label_uri_hans_static": string;
    "label_id": number;
    "bg_style": number;
    "use_img_label": boolean;
}

export interface MyInfoVipOttInfo {
    "vip_type": number;
    "pay_type": number;
    "pay_channel_id": string;
    "status": number;
    "overdue_time": number;
}

export interface MyInfoVipSuperVip {
    "is_super_vip": boolean;
}

/**
 * PlayConf 播放配置
 */
export interface PlayConf {
    /**
     * 是否使用新的描述格式
     */
    "is_new_description": boolean;
}

export interface PollQRCodeData {
    "url": string;
    "refresh_token": string;
    "timestamp": number;
    "code": number;
    "message": string;
}

export interface QRCodeData {
    "url": string;
    "qrcode_key": string;
}

export interface RefreshData {
    "refresh": boolean;
    "timestamp": number;
}

/**
 * SeasonsArchivesData 一个合集内的视频信息
 */
export interface SeasonsArchivesData {
    "aids": number[] | null;
    "page": SeasonsArchivesPage;
    "meta": SeasonsArchivesMeta;
    "archives": SeasonsArchivesItem[] | null;
}

export interface SeasonsArchivesItem {
    "aid": number;
    "bvid": string;
    "ctime": number;
    "duration": number;
    "enable_vt": boolean;
    "interactive_video": boolean;
    "pic": string;
    "playback_position": number;
    "pubdate": number;
    "state": number;
    "stat": SeasonsSeriesArchivesStat;
    "title": string;
    "ugc_pay": number;
    "vt_display": string;
    "is_lesson_video": number;
}

export interface SeasonsArchivesMeta {
    "cover": string;
    "description": string;
    "title": string;
    "category": number;
    "mid": number;
    "ptime": number;
    "season_id": number;

    /**
     * 总数，和Page中的Total一致
     */
    "total": number;
}

export interface SeasonsArchivesPage {
    "PageNum": number;
    "PageSize": number;
    "Total": number;
}

export interface SeasonsItem {
    "archives": SeasonsSeriesArchivesItem[] | null;
    "meta": SeasonsItemMeta;
    "recent_aids": number[] | null;
}

export interface SeasonsItemMeta {
    "category": number;

    /**
     * 合集封面
     */
    "cover": string;

    /**
     * 合集描述
     */
    "description": string;
    "mid": number;
    "name": string;
    "ptime": number;
    "season_id": number;

    /**
     * 合集总量
     */
    "total": number;
    "title": string;
}

export interface SeasonsSeriesArchivesItem {
    "aid": number;
    "bvid": string;
    "ctime": number;
    "duration": number;
    "enable_vt": boolean;
    "interactive_video": boolean;
    "pic": string;
    "playback_position": number;
    "pubdate": number;
    "stat": SeasonsSeriesArchivesStat;
    "state": number;
    "title": string;
    "ugc_pay": number;
    "vt_display": string;
    "is_lesson_video": number;
}

export interface SeasonsSeriesArchivesStat {
    "view": number;
    "vt": number;
    "danmaku": number;
}

export interface SeasonsSeriesData {
    "items_lists": SeasonsSeriesItemsLists;
}

export interface SeasonsSeriesItemsLists {
    "page": SeasonsSeriesPage;
    "seasons_list": SeasonsItem[] | null;
    "series_list": SeriesItem[] | null;
}

export interface SeasonsSeriesPage {
    "page_num": number;
    "page_size": number;

    /**
     * Total 合集+系列的总数
     * 合集+系列
     */
    "total": number;
}

/**
 * SegmentBase 分段基础信息（驼峰命名）
 */
export interface SegmentBase {
    /**
     * 初始化段范围
     */
    "Initialization": string;

    /**
     * 索引段范围
     */
    "indexRange": string;
}

/**
 * SegmentBase1 分段基础信息（下划线命名）
 */
export interface SegmentBase1 {
    /**
     * 初始化段范围
     */
    "initialization": string;

    /**
     * 索引段范围
     */
    "index_range": string;
}

export interface SeriesArchivesData {
    "aids": number[] | null;
    "page": SeriesListPage;
    "archives": SeriesArchivesItem[] | null;
}

export interface SeriesArchivesItem {
    "aid": number;
    "title": string;
    "pubdate": number;
    "ctime": number;
    "state": number;
    "pic": string;
    "duration": number;
    "bvid": string;
    "ugc_pay": number;
    "interactive_video": boolean;
    "enable_vt": number;
    "vt_display": string;
    "desc": string;
    "up_mid": number;
    "stat": SeasonsSeriesArchivesStat;
}

export interface SeriesItem {
    "archives": SeasonsSeriesArchivesItem[] | null;
    "meta": SeriesItemMeta;
    "recent_aids": number[] | null;
}

export interface SeriesItemMeta {
    "category": number;
    "cover": string;
    "creator": string;
    "ctime": number;
    "description": string;
    "keywords": string[] | null;
    "last_update_ts": number;
    "mid": number;
    "mtime": number;
    "name": string;
    "raw_keywords": string;
    "series_id": number;
    "state": number;
    "total": number;
}

export interface SeriesListPage {
    /**
     * 当前页
     */
    "num": number;

    /**
     * 每页数量
     */
    "size": number;

    /**
     * 总数
     */
    "total": number;
}

/**
 * SupportFormat 支持的格式信息
 */
export interface SupportFormat {
    /**
     * 清晰度代码
     */
    "quality": number;

    /**
     * 格式名称
     */
    "format": string;

    /**
     * 新描述
     */
    "new_description": string;

    /**
     * 显示描述（如 "1080P 高清"）
     */
    "display_desc": string;

    /**
     * 上标标签（如 "VIP", "HDR"）
     */
    "superscript": string;

    /**
     * 编码格式列表
     */
    "codecs": string[] | null;

    /**
     * 可观看原因代码
     */
    "can_watch_qn_reason": number;

    /**
     * 限制观看原因代码
     */
    "limit_watch_reason": number;

    /**
     * 上报信息
     */
    "report": { [_ in string]?: any } | null;
}

/**
 * UgcSeason 视频合集信息，不在合集中的视频无此项
 */
export interface UgcSeason {
    "id": number;
    "title": string;
    "cover": string;
    "mid": number;
    "intro": string;
    "sign_state": number;
    "attribute": number;
    "sections": UgcSeasonSectionItem[] | null;
    "stat": UgcSeasonStat;
    "ep_count": number;
    "season_type": number;
    "is_pay_season": boolean;
    "enable_vt": number;
}

export interface UgcSeasonPageItem {
    "cid": number;
    "page": number;
    "from": string;
    "part": string;
    "duration": number;
    "vid": string;
    "weblink": string;
    "dimension": Dimension;
}

export interface UgcSeasonSectionItem {
    "season_id": number;
    "id": number;
    "title": string;
    "type": number;
    "episodes": Episode[] | null;
}

export interface UgcSeasonStat {
    "season_id": number;
    "view": number;
    "danmaku": number;
    "reply": number;
    "fav": number;
    "coin": number;
    "share": number;
    "now_rank": number;
    "his_rank": number;
    "like": number;
    "vt": number;
    "vv": number;
}

export interface UserGarb {
    "url_image_ani_cut": string;
}

export interface UserInfoData {
    "mid": number;
    "name": string;
    "sex": string;
    "face": string;
    "sign": string;
    "rank": number;
    "level": number;
    "birthday": string;
    "is_followed": boolean;
    "is_risk": boolean;
    "vip": UserVip;
}

export interface UserVip {
    /**
     * 会员类型, 0：无会员，1：月度大会员，2：年度及以上大会员
     */
    "type": number;

    /**
     * 会员状态, 0：无效，1：有效
     */
    "status": number;

    /**
     * 会员过期时间, 单位为毫秒时间戳
     */
    "due_date": number;
    "theme_type": number;

    /**
     * 会员标签
     */
    "label": MyInfoVipLabel;

    /**
     * 是否显示会员图标， 0：不显示，1：显示
     */
    "avatar_subscript": number;

    /**
     * 会员昵称颜色
     */
    "nickname_color": string;
    "OttInfo": MyInfoVipOttInfo;
    "super_vip": MyInfoVipSuperVip;

    /**
     * 1: 月度大会员，3： 年度大会员， 7： 十年大会员， 15： 百年大会员
     */
    "role": number;
}

export interface VListItem {
    /**
     * 视频评论数
     */
    "comment": number;
    "typeid": number;

    /**
     * 视频播放数
     */
    "play": number;

    /**
     * 视频封面url
     */
    "pic": string;
    "subtitle": string;
    "description": string;
    "copyright": string;

    /**
     * 视频标题
     */
    "title": string;
    "review": number;
    "author": string;

    /**
     * 视频作者的mid
     */
    "mid": number;

    /**
     * 视频创建时间
     */
    "created": number;

    /**
     * 视频时长，格式为"mm:ss"
     */
    "length": string;
    "video_review": number;

    /**
     * 视频av号
     */
    "aid": number;

    /**
     * 视频bv号
     */
    "bvid": string;
    "hide_click": boolean;
    "is_pay": number;

    /**
     * 是否是联合视频，0：否，1：是
     */
    "is_union_video": number;
    "is_steins_gate": number;
    "is_live_playback": number;
    "is_lesson_video": number;
    "is_lesson_finished": number;
    "lesson_update_info": string;
    "jump_url": string;
    "meta": VideoVListItemMeta;
    "is_avoided": number;
    "season_id": number;
    "attribute": number;
    "is_charging_arc": boolean;
    "elec_arc_type": number;
    "elec_arc_badge": string;
    "vt": number;
    "enable_vt": number;
    "vt_display": string;
    "playback_position": number;
    "is_self_view": boolean;
    "view_self_type": number;
}

export interface VListItemMetaStat {
    "season_id": number;

    /**
     * 播放数
     */
    "view": number;

    /**
     * 弹幕数
     */
    "danmaku": number;
    "reply": number;

    /**
     * 收藏数
     */
    "favorite": number;

    /**
     * 硬币数
     */
    "coin": number;
    "share": number;

    /**
     * 点赞数
     */
    "like": number;
    "mtime": number;
    "vt": number;
    "vv": number;
}

export interface VideoDescV2 {
    "raw_text": string;
    "type": number;
    "biz_id": number;
}

export interface VideoDetailArgueInfo {
    "argue_msg": string;
    "argue_type": number;
    "argue_link": string;
}

/**
 * VideoDetailConciseData 只保留必要的基本信息
 */
export interface VideoDetailConciseData {
    "view": VideoDetailView;
}

export interface VideoDetailView {
    /**
     * 视频分P信息
     */
    "pages": VideoPage[] | null;

    /**
     * 视频1P cid
     */
    "cid": number;
    "bvid": string;
    "aid": number;

    /**
     * 总时长（所有分P），单位为秒
     */
    "duration": number;

    /**
     * 稿件分P总数
     */
    "videos": number;

    /**
     * 视频合集信息，不在合集中的视频无此项
     */
    "ugc_season": UgcSeason;

    /**
     * 视频封面url
     */
    "pic": string;

    /**
     * 视频标题
     */
    "title": string;

    /**
     * 发布时间
     */
    "pubdate": number;

    /**
     * 用户投稿时间
     */
    "ctime": number;

    /**
     * 分区id
     */
    "tid": number;

    /**
     * 分区tid（v2）
     */
    "tid_v2": number;

    /**
     * 子分区名称
     */
    "tname": string;

    /**
     * 子分区名称（v2）
     */
    "tname_v2": string;

    /**
     * 视频类型。1： 原创，2： 转载，3：未填写
     */
    "copyright": number;

    /**
     * 视频简介
     */
    "desc": string;

    /**
     * 新版视频简介
     */
    "desc_v2": VideoDescV2[] | null;

    /**
     * 视频状态
     */
    "state": number;

    /**
     * 稿件参与的活动id
     */
    "mission_id": number;

    /**
     * 视频属性信息
     */
    "rights": VideoViewRights;

    /**
     * UP主信息
     */
    "owner": VideoOwner;

    /**
     * 视频状态
     */
    "stat": VideoViewStat;

    /**
     * 争议/警告信息
     */
    "argue_info": VideoDetailArgueInfo;

    /**
     * 视频同步发布的动态文字内容
     */
    "dynamic": string;

    /**
     * 视频1P 分辨率
     */
    "dimension": Dimension;
    "season_id": number;
    "premiere": any;
    "teenage_mode": number;
    "is_chargeable_season": boolean;

    /**
     * 是否为动态视频
     */
    "is_story": boolean;

    /**
     * 是否为充电专属视频
     */
    "is_upower_exclusive": boolean;

    /**
     * 充电专属视频是否支持试看
     */
    "is_upower_play": boolean;
    "is_upower_preview": boolean;
    "enable_vt": number;
    "vt_display": string;
    "is_upower_exclusive_with_qa": boolean;
    "no_cache": boolean;
    "subtitle": VideoSubTitle;
    "is_season_display": boolean;

    /**
     * 用户装扮信息
     */
    "user_garb": UserGarb;
    "honor_reply": any;
    "like_icon": string;
    "need_jump_bv": boolean;
    "disable_show_up_info": boolean;
    "is_story_play": number;

    /**
     * 是否为作者本人观看
     */
    "is_view_self": boolean;
}

/**
 * VideoItem DASH 视频流项
 */
export interface VideoItem {
    /**
     * 视频流 ID（与清晰度对应）
     */
    "id": number;

    /**
     * 主播放地址（驼峰命名）
     */
    "baseUrl": string;

    /**
     * 主播放地址（下划线命名）
     */
    "base_url": string;

    /**
     * 备用播放地址列表（驼峰命名）
     */
    "backupUrl": string[] | null;

    /**
     * 备用播放地址列表（下划线命名）
     */
    "backup_url": string[] | null;

    /**
     * 码率，单位 bps
     */
    "bandwidth": number;

    /**
     * MIME 类型（驼峰命名）
     */
    "mimeType": string;

    /**
     * MIME 类型（下划线命名）
     */
    "mime_type": string;

    /**
     * 编码格式（如 "avc1.640028"）
     */
    "codecs": string;

    /**
     * 视频宽度
     */
    "width": number;

    /**
     * 视频高度
     */
    "height": number;

    /**
     * 帧率（驼峰命名）
     */
    "frameRate": string;

    /**
     * 帧率（下划线命名）
     */
    "frame_rate": string;

    /**
     * 像素宽高比（Sample Aspect Ratio）
     */
    "sar": string;

    /**
     * SAP 类型（驼峰命名）
     */
    "startWithSap": number;

    /**
     * SAP 类型（下划线命名）
     */
    "start_with_sap": number;

    /**
     * 分段信息（驼峰命名）
     */
    "SegmentBase": SegmentBase;

    /**
     * 分段信息（下划线命名）
     */
    "segment_base": SegmentBase1;

    /**
     * 编码器 ID：7=AVC, 12=HEVC, 13=AV1
     */
    "codecid": number;
}

export interface VideoList {
    "slist": any[] | null;
    "tlist": any;
    "vlist": VListItem[] | null;
}

/**
 * VideoListData UP主视频列表数据
 */
export interface VideoListData {
    "list": VideoList;
    "page": VideoListPage;
    "episodic_button": EpisodicButton;
    "is_risk": boolean;
    "gaia_res_type": number;
    "gaia_data": any;
}

export interface VideoListPage {
    "pn": number;
    "ps": number;
    "count": number;
}

export interface VideoOwner {
    "mid": number;
    "name": string;
    "face": string;
}

export interface VideoPage {
    "cid": number;

    /**
     * 分P页码，从1开始
     */
    "page": number;

    /**
     * 视频来源，如 "vupload"（UP主上传）， hunan：芒果TV，qq： 腾讯视频
     */
    "from": string;

    /**
     * 分P标题
     */
    "part": string;

    /**
     * 分P时长，单位秒
     */
    "duration": number;

    /**
     * 站外视频vid
     */
    "vid": string;

    /**
     * 站外视频跳转url
     */
    "weblink": string;
    "dimension": Dimension;
    "first_frame": string;
    "ctime": number;
}

export interface VideoStat {
    "aid": number;
    "view": number;
    "danmaku": number;
    "reply": number;
    "fav": number;
    "coin": number;
    "share": number;
    "now_rank": number;
    "his_rank": number;
    "like": number;
    "dislike": number;
    "evaluation": string;
    "argue_msg": string;
    "vt": number;
    "vv": number;
}

export interface VideoSubTitle {
    "allow_submit": boolean;
    "list": any[] | null;
}

/**
 * VideoURLData 视频播放地址数据（来自 /x/player/playurl 接口）
 */
export interface VideoURLData {
    /**
     * 请求来源，通常为 "local"
     */
    "from": string;

    /**
     * 结果标识，通常为 "suee"
     */
    "result": string;

    /**
     * 错误信息，成功时为 "0"
     */
    "message": string;

    /**
     * 当前视频清晰度代码（qn值）
     */
    "quality": number;

    /**
     * 视频格式，如 "flv", "mp4", "dash"
     */
    "format": string;

    /**
     * 视频总时长，单位毫秒
     */
    "timelength": number;

    /**
     * 支持的格式列表
     */
    "accept_format": string;

    /**
     * 支持的清晰度描述列表
     */
    "accept_description": string[] | null;

    /**
     * 支持的清晰度代码列表
     */
    "accept_quality": number[] | null;

    /**
     * 视频编码 ID：7=AVC, 12=HEVC, 13=AV1
     */
    "video_codecid": number;

    /**
     * 拖拽参数类型
     */
    "seek_param": string;

    /**
     * 拖拽类型
     */
    "seek_type": string;

    /**
     * DASH 流信息（音视频分离）
     */
    "dash": Dash;

    /**
     * 支持的格式详细信息
     */
    "support_formats": SupportFormat[] | null;

    /**
     * 高码率格式信息（通常为 null）
     */
    "high_format": any;

    /**
     * 音量响度标准化信息
     */
    "volume": Volume;

    /**
     * 上次播放位置，单位秒
     */
    "last_play_time": number;

    /**
     * 上次播放的分P CID
     */
    "last_play_cid": number;

    /**
     * 观看信息（通常为 null）
     */
    "view_info": any;

    /**
     * 播放配置
     */
    "play_conf": PlayConf;

    /**
     * 当前语言
     */
    "cur_language": string;

    /**
     * 当前制作类型
     */
    "cur_production_type": number;

    /**
     * 自动清晰度响应
     */
    "auto_qn_resp": AutoQnResp;
}

export interface VideoVListItemMeta {
    "id": number;
    "title": string;
    "cover": string;
    "mid": number;
    "intro": string;
    "sign_state": number;
    "attribute": number;
    "stat": VListItemMetaStat;
    "ep_count": number;
    "first_aid": number;
    "ptime": number;
    "ep_num": number;
    "show": number;
}

/**
 * VideoViewRights 视频属性信息
 */
export interface VideoViewRights {
    /**
     * 是否允许承包
     */
    "bp": number;

    /**
     * 是否支持充电
     */
    "elec": number;

    /**
     * 是否允许下载
     */
    "download": number;

    /**
     * 是否电影
     */
    "movie": number;
    "pay": number;

    /**
     * 是否有高码率
     */
    "hd5": number;

    /**
     * 是否显示“禁止转载”信息
     */
    "no_reprint": number;

    /**
     * 是否自动播放
     */
    "autoplay": number;
    "ugc_pay": number;

    /**
     * 是否为合作视频
     */
    "is_cooperation": number;
    "ugc_pay_preview": number;
    "no_background": number;
    "clean_mode": number;

    /**
     * 是否为全景视频
     */
    "is_stein_gate": number;
    "is_360": number;
    "no_share": number;
    "arc_pay": number;
    "free_watch": number;
}

export interface VideoViewStat {
    /**
     * 视频aid
     */
    "aid": number;

    /**
     * 视频播放量
     */
    "view": number;

    /**
     * 视频弹幕数
     */
    "danmaku": number;
    "reply": number;

    /**
     * 视频收藏数
     */
    "favorite": number;

    /**
     * 视频投币数
     */
    "coin": number;
    "share": number;
    "now_rank": number;
    "his_rank": number;

    /**
     * 	视频点赞数
     */
    "like": number;

    /**
     * 	视频点踩数
     */
    "dislike": number;
    "evaluation": string;
    "vt": number;
}

/**
 * Volume 音量响度标准化信息（用于统一不同视频的音量）
 */
export interface Volume {
    /**
     * 测量响度（Integrated Loudness）
     */
    "measured_i": number;

    /**
     * 测量响度范围（Loudness Range）
     */
    "measured_lra": number;

    /**
     * 测量真峰值（True Peak）
     */
    "measured_tp": number;

    /**
     * 测量阈值
     */
    "measured_threshold": number;

    /**
     * 目标偏移量
     */
    "target_offset": number;

    /**
     * 目标响度
     */
    "target_i": number;

    /**
     * 目标真峰值
     */
    "target_tp": number;

    /**
     * 多场景参数
     */
    "multi_scene_args": VolumeMultiSceneArgs;
}

/**
 * VolumeMultiSceneArgs 音量多场景参数
 */
export interface VolumeMultiSceneArgs {
    /**
     * 高动态范围目标响度
     */
    "high_dynamic_target_i": string;

    /**
     * 普通目标响度
     */
    "normal_target_i": string;

    /**
     * 小尺寸目标响度
     */
    "undersized_target_i": string;
}
