// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchResolvePlayUrl 批量解析播放地址。单条失败只写入该条结果，不中断整批解析。
 * 每条结果解析完成后会通过 bilibili-playurl-resolved 事件推送给前端，实现渐进式 UI 更新。
 */
export function BatchResolvePlayUrl(reqs: $models.PlayUrlRequest[] | null): $CancellablePromise<$models.PlayUrlResult[] | null> {
    return $Call.ByID(210767095, reqs);
}

/**
 * ClearDownloadHistory 清空 B 站下载历史；只清理缓存记录，不删除已经保存到本地的视频文件。
 */
export function ClearDownloadHistory(): $CancellablePromise<void> {
    return $Call.ByID(2432889835);
}

/**
 * Collection 获取：我追的合集列表, 默认pn：1, ps: 50
 */
export function Collection(pn: number, ps: number): $CancellablePromise<model$0.CollectionData> {
    return $Call.ByID(1558485620, pn, ps);
}

/**
 * CollectionItem 获取合集下的视频, seasonId: model.CollectionDataList.ID
 * 这个接口没有分页，可能是认为获取的合集数量比较少，不需要分页
 */
export function CollectionItem(seasonId: string, pn: number, ps: number): $CancellablePromise<model$0.CollectionItemData> {
    return $Call.ByID(2699614795, seasonId, pn, ps);
}

/**
 * DeleteDownloadHistory 删除单条下载历史；只清理缓存记录，不删除已经保存到本地的视频文件。
 */
export function DeleteDownloadHistory(cid: number): $CancellablePromise<void> {
    return $Call.ByID(3586557993, cid);
}

/**
 * DownloadCover 下载视频封面到当前下载目录，返回保存后的文件路径。
 */
export function DownloadCover(cover: string, task: $models.DashDownloadTask): $CancellablePromise<string> {
    return $Call.ByID(914802387, cover, task);
}

/**
 * DownloadHistory 返回后端下载缓存记录；只读历史页使用，下载接口本身不暴露缓存命中细节。
 */
export function DownloadHistory(): $CancellablePromise<model$0.DownloadHistoryItem[] | null> {
    return $Call.ByID(933930544);
}

/**
 * DownloadVideoByDash 下载单个视频，保留旧入口以兼容前端或其他调用方。
 */
export function DownloadVideoByDash(sourceName: string, bvid: string, title: string, videoURL: string, audioURL: string): $CancellablePromise<string> {
    return $Call.ByID(3425201982, sourceName, bvid, title, videoURL, audioURL);
}

/**
 * DownloadVideosByDash 批量下载 DASH 任务；后端负责并发、失败隔离和每个任务后的休眠控制。
 */
export function DownloadVideosByDash(tasks: $models.DashDownloadTask[] | null): $CancellablePromise<$models.DashDownloadBatchResult> {
    return $Call.ByID(598649125, tasks);
}

/**
 * DownloadVideosByDashIncremental 增量下载：跳过已下载的视频，只下载新增部分。
 */
export function DownloadVideosByDashIncremental(tasks: $models.DashDownloadTask[] | null): $CancellablePromise<$models.DashDownloadBatchResult> {
    return $Call.ByID(3214500723, tasks);
}

/**
 * DynamicVideos 获取当前登录账号关注动态中的全部视频动态。
 */
export function DynamicVideos(): $CancellablePromise<model$0.DynamicArchiveItem[] | null> {
    return $Call.ByID(3605661009);
}

/**
 * DynamicVideosPage 获取当前登录账号关注动态中的单页视频动态。
 */
export function DynamicVideosPage(offset: string): $CancellablePromise<model$0.DynamicArchivePage> {
    return $Call.ByID(1150526418, offset);
}

/**
 * Favorites 收藏夹详情，包含元数据和视频列表
 * mediaId: model.FavoriteItem 中的id字段; pn: 页码, 默认是1;  ps: 每页数量, 默认40
 */
export function Favorites(mediaId: number, pn: number, ps: number): $CancellablePromise<model$0.FavoriteData> {
    return $Call.ByID(2855101141, mediaId, pn, ps);
}

/**
 * FavoritesList 获取自己的收藏列表，这里不处理他人的收藏列表了
 */
export function FavoritesList(): $CancellablePromise<model$0.FavoritesData> {
    return $Call.ByID(2915442673);
}

/**
 * FilterIncrementalTasks 将任务分为待下载和已下载两组；已下载项附带当时保存的文件路径。
 */
export function FilterIncrementalTasks(tasks: $models.DashDownloadTask[] | null): $CancellablePromise<[$models.DashDownloadTask[] | null, $models.DashDownloadResult[] | null]> {
    return $Call.ByID(3341548992, tasks);
}

export function FollowList(pn: number, ps: number): $CancellablePromise<model$0.FollowData> {
    return $Call.ByID(1217461265, pn, ps);
}

/**
 * Info 用户空间
 */
export function Info(spaceURLOrMid: string): $CancellablePromise<model$0.UserInfoData> {
    return $Call.ByID(3678888260, spaceURLOrMid);
}

/**
 * IsLoggedIn 检测是否已登录, 通过检查数据库中是否存在有效的 cookies 来判断登录状态
 */
export function IsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(2674201361);
}

/**
 * IsRefresh 是否需要刷新
 */
export function IsRefresh(): $CancellablePromise<model$0.RefreshData> {
    return $Call.ByID(2420496315);
}

/**
 * LogOut 退出登录, 通过调用退出登录接口并清除本地保存的 cookies 来实现退出登录功能
 */
export function LogOut(): $CancellablePromise<model$0.LogOut> {
    return $Call.ByID(3910157566);
}

/**
 * MyInfo 个人资料
 */
export function MyInfo(): $CancellablePromise<model$0.MyInfoProfile> {
    return $Call.ByID(2389020218);
}

/**
 * PollQRCode 轮询二维码状态, 直到扫码成功或二维码过期
 */
export function PollQRCode(qrcodeKey: string): $CancellablePromise<model$0.PollQRCodeData> {
    return $Call.ByID(3317413527, qrcodeKey);
}

/**
 * QRCode 获取二维码, 180秒内有效
 */
export function QRCode(): $CancellablePromise<model$0.QRCodeData> {
    return $Call.ByID(3876720066);
}

/**
 * RefreshCookie 刷新登录 Cookie 和 refresh_token。
 */
export function RefreshCookie(): $CancellablePromise<model$0.CookieRefreshData> {
    return $Call.ByID(1341335101);
}

/**
 * ResolvePlayUrl 解析单个视频的播放地址，内部由模块级信号量控制并发。
 * totalCount 为本次批量解析的总视频数，当数量不超过并发上限时跳过休眠以提升体验。
 */
export function ResolvePlayUrl(req: $models.PlayUrlRequest, totalCount: number): $CancellablePromise<$models.PlayUrlResult> {
    return $Call.ByID(3065194543, req, totalCount);
}

/**
 * SearchDownloadHistory 获取历史搜索记录
 * Deprecated: 该接口已废弃，搜索历史记录功能已迁移到前端实现，后端不再维护搜索历史记录
 */
export function SearchDownloadHistory(upperNameOrTitle: string): $CancellablePromise<model$0.DownloadHistoryItem[] | null> {
    return $Call.ByID(3933691036, upperNameOrTitle);
}

/**
 * SeasonsArchivesList 获取一个合集的视频列表
 */
export function SeasonsArchivesList(upMid: string, pageSize: number, pageNum: number, seasonId: number): $CancellablePromise<model$0.SeasonsArchivesData> {
    return $Call.ByID(2454146269, upMid, pageSize, pageNum, seasonId);
}

/**
 * SeasonsSeriesList 获取合集|系列列表, 这个使用的接口是：https://api.bilibili.com/x/polymer/web-space/seasons_series_list
 * https://api.bilibili.com/x/polymer/web-space/home/seasons_series返回的不全
 * 投稿总量：视频+图文+音频
 */
export function SeasonsSeriesList(upMid: string, pageSize: number, pageNum: number): $CancellablePromise<model$0.SeasonsSeriesData> {
    return $Call.ByID(3467695395, upMid, pageSize, pageNum);
}

/**
 * SeriesList 获取一个系列的视频列表, 这个接口和合集视频列表的接口不一样
 */
export function SeriesList(upMid: string, ps: number, pn: number, seriesId: number): $CancellablePromise<model$0.SeriesArchivesData> {
    return $Call.ByID(463149409, upMid, ps, pn, seriesId);
}

/**
 * VideoDetailConcise 通过 AV 号获取精简详情
 */
export function VideoDetailConcise(aid: number): $CancellablePromise<model$0.VideoDetailConciseData> {
    return $Call.ByID(1166511714, aid);
}

/**
 * VideoDetailConciseBvid 通过 BV 号获取精简详情（便于粘贴链接）
 */
export function VideoDetailConciseBvid(bvid: string): $CancellablePromise<model$0.VideoDetailConciseData> {
    return $Call.ByID(3006313647, bvid);
}

/**
 * VideoList 获取视频列表。mid 为用户 ID，ps 为每页数量，pn 为页码
 */
export function VideoList(mid: number, ps: number, pn: number): $CancellablePromise<model$0.VideoListData> {
    return $Call.ByID(527413907, mid, ps, pn);
}

/**
 * VideoPlayURL 获取播放地址。qn 为清晰度代码（如 80=1080P）；fnval 为流格式掩码（如 4048=DASH，0=FLV，80=MP4 等）。qn≤0 时默认 80，fnval<0 时默认 4048（0 表示 FLV 合法，不可再用负数表示默认）。
 */
export function VideoPlayURL(avid: number, bvid: string, cid: number, qn: number): $CancellablePromise<model$0.VideoURLData> {
    return $Call.ByID(4261353618, avid, bvid, cid, qn);
}
