// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * HistoryPage 下载历史的一页：keyword 为空时 Total 是全部记录数，非空时是
 * 匹配记录数；HasMore 表示过滤后仍有下一页。
 */
export interface HistoryPage {
    "items": model$0.DownloadHistoryItem[] | null;
    "total": number;
    "hasMore": boolean;
}

export interface PlayUrlRequest {
    "bvid": string;
    "cid": number;
    "qn": number;
}

export interface PlayUrlResult {
    "bvid": string;
    "cid": number;
    "requestCid": number;
    "error"?: string;
    "detail"?: model$0.VideoDetailConciseData | null;
    "play_url"?: model$0.VideoURLData | null;
}
