// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export interface PlayUrlRequest {
    "bvid": string;
    "cid": number;
    "qn": number;
}

export interface PlayUrlResult {
    "bvid": string;
    "cid": number;
    "requestCid": number;
    "error"?: string;
    "detail"?: model$0.VideoDetailConciseData | null;
    "play_url"?: model$0.VideoURLData | null;
}
