// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function FFmpegPath(): $CancellablePromise<string> {
    return $Call.ByID(2847638989);
}

/**
 * GetBilibiliDefaultQN returns the preferred Bilibili quality ID, when set.
 */
export function GetBilibiliDefaultQN(): $CancellablePromise<string> {
    return $Call.ByID(3773347533);
}

/**
 * GetCloseToTray 获取关闭按钮行为设置。
 */
export function GetCloseToTray(): $CancellablePromise<boolean> {
    return $Call.ByID(379760918);
}

/**
 * GetConcurrencyNum 获取同时下载的视频数量
 */
export function GetConcurrencyNum(): $CancellablePromise<number> {
    return $Call.ByID(2563603988);
}

/**
 * GetParsePlayURLNum 获取同时BiliBili解析播放链接的数量，默认为3
 */
export function GetParsePlayURLNum(): $CancellablePromise<number> {
    return $Call.ByID(2120884529);
}

/**
 * GetParsePlayURLNumSafe 获取并发解析数，出错时返回默认值 3
 */
export function GetParsePlayURLNumSafe(): $CancellablePromise<number> {
    return $Call.ByID(3627612756);
}

export function GetParsePlayURLSleep(): $CancellablePromise<number> {
    return $Call.ByID(3659190406);
}

/**
 * GetParsePlayURLSleepSafe 获取解析后随机休眠上限（秒），默认 5
 */
export function GetParsePlayURLSleepSafe(): $CancellablePromise<number> {
    return $Call.ByID(371301907);
}

export function GetSavePreference(): $CancellablePromise<boolean> {
    return $Call.ByID(1008438865);
}

/**
 * GetSleepTime 下载完一个视频之后的休眠时间；配置值按“秒”保存，避免把默认值 60 误解释成 60 纳秒。
 */
export function GetSleepTime(): $CancellablePromise<number> {
    return $Call.ByID(3794916405);
}

/**
 * GetStorage 获取存储目录设置
 */
export function GetStorage(): $CancellablePromise<string> {
    return $Call.ByID(1243933626);
}

/**
 * GetTheme 获取主题设置
 */
export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(103558246);
}

/**
 * GetVersion returns the current version of the application.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2092884539);
}

/**
 * HasCloseToTrayChoice 检查用户是否已对关闭行为做出选择（key 是否存在）。
 */
export function HasCloseToTrayChoice(): $CancellablePromise<boolean> {
    return $Call.ByID(312461585);
}

/**
 * HasFFmpeg 检查系统中是否可用 ffmpeg
 */
export function HasFFmpeg(): $CancellablePromise<boolean> {
    return $Call.ByID(2353954040);
}

export function IsAutoUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(2576526785);
}

/**
 * IsCloseToTray 返回用户选择：true=缩小到托盘，false=退出程序。未选择时默认返回 true。
 */
export function IsCloseToTray(): $CancellablePromise<boolean> {
    return $Call.ByID(1155197624);
}

/**
 * OpenDownloadLocation 打开下载历史中的文件位置.
 */
export function OpenDownloadLocation(path: string): $CancellablePromise<void> {
    return $Call.ByID(2678787160, path);
}

/**
 * OpenLocalFile 使用系统默认程序打开下载历史中的本地文件或目录.
 */
export function OpenLocalFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(2344555772, path);
}

export function SetAutoUpdate(enable: boolean): $CancellablePromise<void> {
    return $Call.ByID(2869161031, enable);
}

/**
 * SetCloseToTray 设置关闭按钮行为：false=退出程序，true=缩小到托盘。
 */
export function SetCloseToTray(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(59508042, v);
}

/**
 * SetConcurrencyNum 保存同时下载的视频数量
 */
export function SetConcurrencyNum(num: number): $CancellablePromise<void> {
    return $Call.ByID(2095982176, num);
}

export function SetFFmpegPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(2487329511, path);
}

export function SetParsePlayURLNum(num: number): $CancellablePromise<void> {
    return $Call.ByID(3022290829, num);
}

export function SetParsePlayURLSleep(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(3502788594, seconds);
}

/**
 * SetSavePreference 保存时是否自动分组
 */
export function SetSavePreference(allowGroup: boolean): $CancellablePromise<void> {
    return $Call.ByID(1839644909, allowGroup);
}

/**
 * SetSleepTime 保存休眠秒数；前端传入 time.Duration 时统一落库为秒，便于用户理解和配置。
 */
export function SetSleepTime(d: number): $CancellablePromise<void> {
    return $Call.ByID(3627690169, d);
}

/**
 * SetStoragePath 保存存储目录。
 */
export function SetStoragePath(dir: string): $CancellablePromise<void> {
    return $Call.ByID(594889173, dir);
}

/**
 * SetTheme 设置主题，前端调用时会传入 "light"、"dark"等，落库保存供下次启动时加载使用
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(2810596410, theme);
}
