// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Result {
    /**
     * 是否有新版本可用
     */
    "available": boolean;

    /**
     * 当前版本
     */
    "currentVersion": string;

    /**
     * 最新版本
     */
    "latestVersion": string;

    /**
     * 下载链接
     */
    "downloadURL": string;

    /**
     * 发布说明
     */
    "releaseNotes": string;
}
