// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadUpdate downloads an update package and emits progress events.
 */
export function DownloadUpdate(downloadURL: string): $CancellablePromise<string> {
    return $Call.ByID(680841022, downloadURL);
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(3082522119);
}

/**
 * InstallUpdate starts the standalone updater and exits the current process.
 */
export function InstallUpdate(packagePath: string): $CancellablePromise<void> {
    return $Call.ByID(906486899, packagePath);
}

export function IsAutoUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(2722372653);
}

/**
 * LatestResult lets the frontend recover a result if the startup event was
 * emitted before its event listener was registered.
 */
export function LatestResult(): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(28414177);
}

/**
 * NeedUpdate performs an explicit update check for frontend callers.
 */
export function NeedUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(3532925518);
}

export function SetAutoUpdate(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2353761115, enabled);
}
