// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AudioMeta {
    /**
     * 音频比特率
     */
    "bitrate": number;

    /**
     * 音频编码类型，比如：bytevc1
     */
    "codec_type": string;

    /**
     * normal等
     */
    "encoded_type": string;

    /**
     * 音频文件的Hash值, 用于校验文件完整性
     */
    "file_hash": string;

    /**
     * 音频格式, 例如 "dash"
     */
    "format": string;

    /**
     * 音频文件ID
     */
    "file_id": string;

    /**
     * 音频帧率
     */
    "fps": number;

    /**
     * 音频logo类型, 例如 "normal"
     */
    "logo_type": string;

    /**
     * audio
     */
    "media_type": string;

    /**
     * 音频数据大小, 单位为字节
     */
    "size": number;

    /**
     * 音频质量描述，比如：normal
     */
    "quality": string;

    /**
     * 音频质量描述，比如：普通
     */
    "quality_desc": string;

    /**
     * 音频额外信息
     */
    "sub_info": string;

    /**
     * 音频URL列表
     */
    "url_list": AudioMetaUrlList;
}

export interface AudioMetaUrlList {
    "backup_url": string;
    "fallback_url": string;
    "main_url": string;
}

export interface Author {
    /**
     * 作者头像列表
     */
    "cover_url": Avatar[] | null;

    /**
     * 作者头像
     */
    "avatar_thumb": Avatar;

    /**
     * 作者头像
     */
    "avatar_larger": Avatar;

    /**
     * 关注状态
     */
    "follow_status": number;

    /**
     * 粉丝状态
     */
    "follower_status": number;

    /**
     * 作者昵称
     */
    "nickname": string;

    /**
     * 作者用户ID
     */
    "uid": string;

    /**
     * 作者sec_uid
     */
    "sec_uid": string;
}

export interface Avatar {
    "height": number;
    "width": number;
    "uri": string;
    "url_list": string[] | null;
}

/**
 * AwemeItem 视频信息
 */
export interface AwemeItem {
    /**
     * 视频ID
     */
    "aweme_id": string;

    /**
     * 视频标题+#标签
     */
    "desc": string;

    /**
     * 视频创建时间
     */
    "create_time": number;

    /**
     * 视频作者信息
     */
    "author": Author;
    "music": Music;

    /**
     * 视频信息
     */
    "video": Video;
    "statistics": VideoStatistics;

    /**
     * 视频时长, 单位为毫秒
     */
    "duration": number;
    "aweme_type": number;

    /**
     * 视频作者的用户ID
     */
    "author_user_id": number;

    /**
     * 视频发布的地区:CN等
     */
    "region": string;
    "group_id": string;
    "prevent_download": boolean;
    "is_moment_history": number;
    "is_moment_story": number;
    "sec_item_id": string;
    "item_aigc_follow_shot": number;

    /**
     * 图文类型视频使用这个字段中的图片列表
     */
    "images": ImageItem[] | null;
    "origin_duet_resource_uri": string;
    "is_image_beat": boolean;

    /**
     * 视频置顶状态，1是置顶，0不是
     */
    "is_top": number;
    "is_life_item": boolean;
    "author_mask_tag": number;
    "user_recommend_status": number;
    "collection_corner_mark": number;
    "is_share_post": boolean;

    /**
     * 视频的认证token
     */
    "authentication_token": string;

    /**
     * 视频类型，2图文，4视频
     */
    "media_type": number;
    "activity_video_type": number;
    "boost_status": number;

    /**
     * 视频标题，带标签，可能为空
     */
    "caption": string;

    /**
     * 子标题，可能为空
     */
    "item_title": string;
    "original": number;
    "luna_video_candidate_status"?: string;
    "is_multi_content"?: number;
    "image_item_quality_level"?: number;

    /**
     * 是否是动图，1是，0不是
     */
    "is_live_photo": number;

    /**
     * 有这个字段，一定是动图，并且是多张动图，没有这个的也不一定不是动图
     */
    "is_slides": boolean;
}

export interface BigThumbItem {
    /**
     * 视频时长, 单位为秒
     */
    "duration": number;

    /**
     * 视频封面图片格式, 例如 "jpg"
     */
    "fext": string;
    "img_num": number;
    "img_url": string;
    "img_urls": string[] | null;
    "img_x_len": number;
    "img_y_len": number;
    "img_x_size": number;
    "img_y_size": number;
    "interval": number;
    "uri": string;
    "uris": string[] | null;
}

export interface BitRateAudioItem {
    /**
     * 需要json unmarshal
     */
    "audio_extra": string;
    "audio_meta": AudioMeta;

    /**
     * 音频质量
     */
    "audio_quality": number;
}

export interface BitRateItem {
    "FPS": number;
    "HDR_bit": string;
    "HDR_type": string;
    "bit_rate": number;

    /**
     * 视频格式, 例如 "dash","mp4"
     */
    "format": string;
    "gear_name": string;
    "is_bytevc1": number;
    "is_h265": number;
    "play_addr": PlayInfo;
    "quality_type": number;
    "video_extra": string;
}

export interface Chorus {
    "start_ms": number;
    "duration_ms": number;
}

/**
 * CollectListResponse 收藏夹列表响应
 */
export interface CollectListResponse {
    /**
     * 偏移量
     */
    "cursor": number;

    /**
     * 收藏夹总数
     */
    "total_number": number;

    /**
     * 成功是0
     */
    "status_code": number;

    /**
     * 是否还有更多数据
     */
    "has_more": boolean;

    /**
     * 收藏夹列表
     */
    "collects_list": CollectsList[] | null;
}

export interface CollectionItem {
    /**
     * 合集作者信息
     */
    "author": Author;

    /**
     * 合集封面URL
     */
    "cover_url": Cover;

    /**
     * 合集创建时间
     */
    "create_time": number;

    /**
     * 合集描述
     */
    "desc": string;
    "is_serial_mix": number;

    /**
     * 合集ID
     */
    "mix_id": string;

    /**
     * 合集名称
     */
    "mix_name": string;

    /**
     * 合集类型，暂未探明
     */
    "mix_type": number;
    "update_time": number;

    /**
     * 合集统计信息
     */
    "statis": CollectionStatistic;
}

/**
 * CollectionListResponse 获取合集下的视频列表响应
 */
export interface CollectionListResponse {
    "status_code": number;
    "status_msg": string;
    "has_more": number;
    "max_cursor": number;
    "min_cursor": number;
    "aweme_list": AwemeItem[] | null;
}

export interface CollectionResponse {
    /**
     * 下一页的偏移量
     */
    "cursor": number;

    /**
     * 是否还有更多数据
     */
    "has_more": number;

    /**
     * 成功是0
     */
    "status_code": number;

    /**
     * 合集列表
     */
    "mix_infos": CollectionItem[] | null;
}

/**
 * CollectionStatistic 合集统计信息，下面两个字段一样
 */
export interface CollectionStatistic {
    /**
     * 合集数量
     */
    "has_updated_episode": number;

    /**
     * 合集数量
     */
    "updated_to_episode": number;
}

export interface CollectsList {
    "app_id": number;

    /**
     * 收藏夹封面
     */
    "collects_cover": Cover;

    /**
     * 收藏夹ID
     */
    "collects_id": number;

    /**
     * 收藏夹ID的字符串形式
     */
    "collects_id_str": string;

    /**
     * 收藏夹名称
     */
    "collects_name": string;

    /**
     * 创建时间
     */
    "create_time": number;
    "follow_status": number;
    "followed_count": number;
    "is_default_cover": boolean;
    "is_normal_status": boolean;
    "item_type": number;
    "last_collect_time": number;
    "play_count": number;
    "sicily_collects_cover_list": any;
    "states": number;
    "status": number;
    "system_type": number;

    /**
     * 收藏夹内视频总数
     */
    "total_number": number;
    "user_id": number;

    /**
     * 用户ID的字符串形式
     */
    "user_id_str": string;
    "user_info": UserInfo;
}

export interface Cover {
    "uri": string;
    "url_list": string[] | null;
    "width": number;
    "height": number;
}

/**
 * FavoriteVideoResponse 收藏视频列表响应
 */
export interface FavoriteVideoResponse {
    /**
     * 下一页的偏移量
     */
    "cursor": number;

    /**
     * 是否还有更多数据
     */
    "has_more": number;

    /**
     * 成功是0
     */
    "status_code": number;

    /**
     * 用户ID
     */
    "uid": string;

    /**
     * 用户sec_uid, 接口返回的是空字符串
     */
    "sec_uid": string;

    /**
     * 收藏视频列表
     */
    "aweme_list": AwemeItem[] | null;
}

export interface FollowItem {
    /**
     * 个性签名
     */
    "signature": string;

    /**
     * 作品数量
     */
    "aweme_count": number;

    /**
     * 昵称
     */
    "nickname": string;
    "sec_uid": string;
    "uid": string;
    "unique_id": string;

    /**
     * 和unique_id一样
     */
    "short_id": string;
    "avatar_larger": Avatar;
    "avatar_medium": Avatar;
    "avatar_thumb": Avatar;

    /**
     * 粉丝数量
     */
    "follower_count": number;
}

/**
 * FollowResponse 关注列表
 */
export interface FollowResponse {
    "followings": FollowItem[] | null;

    /**
     * 是否还有更多数据
     */
    "has_more": boolean;

    /**
     * 成功是0
     */
    "status_code": number;

    /**
     * 总关注人数，和mix_count相等
     */
    "total": number;
    "mix_count": number;

    /**
     * 自己的用户ID
     */
    "myself_user_id": string;

    /**
     * 当前页的偏移量，默认是20，即每次请求20条数据
     */
    "offset": number;
}

export interface HistoryItem {
    "author": Author;

    /**
     * 视频ID
     */
    "aweme_id": string;

    /**
     * 抖音业务类型码，辅助排查类型差异
     */
    "aweme_type": number;

    /**
     * 标题，可能为空
     */
    "caption": string;

    /**
     * 发布时间
     */
    "create_time": number;

    /**
     * 标题+#标签
     */
    "desc": string;

    /**
     * 图文/动图素材列表
     */
    "images": ImageItem[] | null;

    /**
     * 1 表示动图
     */
    "is_live_photo": number;

    /**
     * 多张动图信号
     */
    "is_slides": boolean;

    /**
     * 置顶状态，1 是置顶
     */
    "is_top": number;

    /**
     * 子标题，可能为空
     */
    "item_title": string;

    /**
     * 2 图文，4 普通视频，42 常见于动图/Live Photo
     */
    "media_type": number;
    "music": Music;

    /**
     * 视频统计信息
     */
    "statistics": VideoStatistics;
    "video": Video;
}

/**
 * HistoryResponse 观看历史接口的响应
 */
export interface HistoryResponse {
    /**
     * 是否有更多数据，1表示有，0表示没有
     */
    "has_more": number;

    /**
     * 最大游标，下一页请求时传入
     */
    "max_cursor": number;

    /**
     * 状态码，成功时为0
     */
    "status_code": number;

    /**
     * 状态信息，成功时为""
     */
    "status_msg": string;

    /**
     * 观看历史列表
     */
    "aweme_list": HistoryItem[] | null;
}

export interface ImageItem {
    /**
     * / 不带水印的图片下载地址列表
     */
    "url_list": string[] | null;

    /**
     * 剪辑类型 5：动图; 2: 普通图片
     */
    "clip_type": number;

    /**
     * 1: 动图
     */
    "live_photo_type": number;

    /**
     * 动图视频信息，clip_type=5时存在
     */
    "video": ImageVideo;
}

/**
 * ImageVideo 动图Video结构
 */
export interface ImageVideo {
    /**
     * 视频封面
     */
    "cover": Cover;

    /**
     * 视频原始封面
     */
    "origin_cover": Cover;

    /**
     * 视频不同质量的播放地址信息列表, 和play_addr中的一样
     */
    "bit_rate": BitRateItem[] | null;

    /**
     * 视频时长, 单位为秒
     */
    "duration": number;

    /**
     * 视频高度
     */
    "height": number;

    /**
     * 视频宽度
     */
    "width": number;

    /**
     * 视频播放地址信息
     */
    "play_addr_h264": PlayInfo;

    /**
     * 视频播放地址信息
     */
    "play_addr": PlayInfo;

    /**
     * 是否有水印
     */
    "has_watermark": boolean;
}

export interface MatchedPgcSound {
    "author": string;
    "title": string;
    "mixed_title": string;
    "mixed_author": string;
    "cover_medium": Cover;
}

export interface Music {
    "id": number;
    "id_str": string;
    "title": string;
    "author": string;
    "album": string;
    "cover_hd"?: Cover;
    "cover_large"?: Cover;
    "cover_medium"?: Cover;
    "cover_thumb": Cover;
    "play_url": PlayUrl;
    "schema_url": string;
    "source_platform": number;
    "start_time": number;
    "end_time": number;
    "duration": number;
    "user_count": number;
    "collect_stat": number;
    "status": number;
    "offline_desc": string;
    "owner_id": string;
    "owner_nickname": string;
    "is_original": boolean;
    "mid": string;
    "binded_challenge_id": number;
    "redirect": boolean;
    "is_restricted": boolean;
    "author_deleted": boolean;
    "is_del_video": boolean;
    "is_video_self_see": boolean;
    "owner_handle": string;
    "prevent_download": boolean;
    "prevent_item_download_status": number;
    "sec_uid": string;
    "avatar_thumb": Avatar;
    "avatar_medium": Avatar;
    "avatar_large": Avatar;
    "is_commerce_music": boolean;
    "is_original_sound": boolean;
    "audition_duration": number;
    "shoot_duration": number;
    "reason_type": number;
    "dmv_auto_show": boolean;
    "is_pgc": boolean;
    "is_matched_metadata": boolean;
    "is_audio_url_with_cookie": boolean;
    "can_background_play": boolean;
    "music_status": number;
    "video_duration": number;
    "pgc_music_type": number;
    "author_status": number;
    "dsp_status": number;
    "music_collect_count": number;
    "music_cover_atmosphere_color_value": string;
    "song"?: Song;
    "music_image_beats"?: MusicImageBeats;
    "matched_pgc_sound"?: MatchedPgcSound;
}

export interface MusicImageBeats {
    "music_image_beats_url": Cover;
}

export interface MyInfoResponse {
    "status_code": number;
    "user": User;
}

export interface PlayInfo {
    /**
     * 视频数据大小, 单位为字节
     */
    "data_size": number;

    /**
     * 视频文件的CS值, 用于校验文件完整性
     */
    "file_cs": string;

    /**
     * 视频文件的Hash值, 用于校验文件完整性
     */
    "file_hash": string;

    /**
     * 视频高度
     */
    "height": number;

    /**
     * 视频宽度
     */
    "width": number;
    "uri": string;

    /**
     * 视频URL的Key值
     */
    "url_key": string;

    /**
     * 视频URL列表
     */
    "url_list": string[] | null;
}

export interface PlayUrl {
    "uri": string;
    "url_list": string[] | null;
    "width": number;
    "height": number;
    "url_key": string;
}

export interface SearchFollowResponse {
    /**
     * 昵称
     */
    "rich_sug_nickname": string;

    /**
     * 用户ID
     */
    "rich_sug_user_id": string;

    /**
     * 用户sec_uid
     */
    "rich_sug_sec_uid": string;

    /**
     * 关注状态，follow表示已关注
     */
    "rich_sug_follow_status": string;

    /**
     * 关系类型，关注
     */
    "rich_sug_relation_type": string;

    /**
     * 头像URI
     */
    "rich_sug_avatar_uri": string;

    /**
     * 抖音号
     */
    "rich_sug_short_id": string;
}

export interface SeriesInfoItem {
    "author": Author;
    "cover_url": Cover;
    "create_time": number;
    "desc": string;
    "real_name": string;
    "series_name": string;
    "series_id": string;
    "stats": SeriesStat;
}

export interface SeriesStat {
    /**
     * 合集数量
     */
    "updated_to_episode": number;

    /**
     * 合集数量
     */
    "total_episode": number;
}

export interface Song {
    "id": number;
    "id_str": string;
    "title"?: string;
    "chorus"?: Chorus;
}

export interface User {
    "avatar_larger": Avatar;
    "avatar_medium": Avatar;
    "avatar_thumb": Avatar;
    "city": string;

    /**
     * 作品数量
     */
    "aweme_count": number;
    "country": string;

    /**
     * 粉丝数量
     */
    "follower_count": number;

    /**
     * 关注数量
     */
    "following_count": number;

    /**
     * IP所在地
     */
    "ip_location": string;
    "nickname": string;

    /**
     * 省份
     */
    "province": string;

    /**
     * 签名
     */
    "signature": string;
    "uid": string;

    /**
     * 抖音号
     */
    "unique_id": string;

    /**
     * 安全uid，某些接口需要传这个
     */
    "sec_uid": string;
}

export interface UserInfo {
    "avatar_larger": Avatar;
    "avatar_medium": Avatar;
    "avatar_thumb": Avatar;
    "nickname": string;
    "uid": string;
}

export interface UserResponse {
    "user": User;
    "status_code": number;
}

/**
 * UserSeriesResponse 用户空间的合集列表响应
 */
export interface UserSeriesResponse {
    "cursor": number;
    "has_more": number;
    "series_infos": SeriesInfoItem[] | null;
    "status_code": number;
    "status_msg": string;
    "total": number;
}

/**
 * UserVideoListResponse 用户空间的视频列表响应
 */
export interface UserVideoListResponse {
    "aweme_list": AwemeItem[] | null;

    /**
     * 是否还有更多数据，0没有，1有
     */
    "has_more": number;

    /**
     * 成功是0
     */
    "status_code": number;

    /**
     * 上一页的请求参数
     */
    "min_cursor": number;

    /**
     * 作为下一页的请求参数
     */
    "max_cursor": number;
    "post_serial": number;
    "request_item_cursor": number;
    "replace_series_cover": number;
}

/**
 * Video 视频信息，图文类型时，play_addr是mp3格式的音频地址
 */
export interface Video {
    /**
     * 视频封面
     */
    "cover": Cover;

    /**
     * 动态封面
     */
    "dynamic_cover": Cover;

    /**
     * 原始封面
     */
    "raw_cover": Cover;

    /**
     * 视频不同质量的播放地址信息列表
     */
    "bit_rate": BitRateItem[] | null;

    /**
     * 音频信息
     */
    "bit_rate_audio": BitRateAudioItem[] | null;

    /**
     * 大图信息列表
     */
    "big_thumbs": BigThumbItem[] | null;

    /**
     * 视频时长, 单位为秒
     */
    "duration": number;

    /**
     * 视频格式, 例如 "dash"
     */
    "format": string;

    /**
     * 视频高度
     */
    "height": number;

    /**
     * 视频宽度
     */
    "width": number;

    /**
     * 视频播放地址信息
     */
    "play_addr_h264": PlayInfo;

    /**
     * 视频播放地址信息
     */
    "play_addr_265": PlayInfo;

    /**
     * 视频播放地址信息
     */
    "play_addr": PlayInfo;

    /**
     * 视频原始封面
     */
    "origin_cover": Cover;

    /**
     * 视频高斯模糊封面
     */
    "gaussian_cover": Cover;
}

export interface VideoStatistics {
    /**
     * 收藏数
     */
    "collect_count": number;

    /**
     * 评论数
     */
    "comment_count": number;

    /**
     * 点赞数
     */
    "digg_count": number;

    /**
     * 推荐数
     */
    "recommend_count": number;

    /**
     * 分享数
     */
    "share_count": number;
}
