// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Controller owns application-window interactions exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ForceQuit allows the next close event to exit the application.
 */
export function ForceQuit(): $CancellablePromise<void> {
    return $Call.ByID(1531103974);
}

/**
 * HideWindow hides the main window.
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(256980434);
}

/**
 * SelectFFmpegPath opens an executable chooser and persists a validated path.
 */
export function SelectFFmpegPath(): $CancellablePromise<string> {
    return $Call.ByID(2827319556);
}

/**
 * SetStorage opens a directory chooser and persists the selected path.
 */
export function SetStorage(): $CancellablePromise<string> {
    return $Call.ByID(2364433123);
}
