// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * CollectList 收藏夹列表接口，需要分页获取，前端默认10条。cursor参数是偏移量，默认0，即从第0条数据开始返回，每次请求返回10条数据。
 */
export function CollectList(cursor: number): $CancellablePromise<model$0.CollectListResponse> {
    return $Call.ByID(618661398, cursor);
}

/**
 * Collection 收藏的合集
 */
export function Collection(count: number, cursor: number): $CancellablePromise<model$0.CollectionResponse> {
    return $Call.ByID(1311088532, count, cursor);
}

/**
 * CollectionList 合集视频列表
 */
export function CollectionList(secUserID: string, seriesID: string, cursor: number, count: number): $CancellablePromise<model$0.CollectionListResponse> {
    return $Call.ByID(743063260, secUserID, seriesID, cursor, count);
}

/**
 * Dynamic 关注的用户最近发布的动态
 * cursor参数是分页的游标，首次请求传0，后续传上次响应里的cursor
 */
export function Dynamic(cursor: number): $CancellablePromise<model$0.DynamicResponse> {
    return $Call.ByID(2923706537, cursor);
}

/**
 * FavoriteVideo 收藏的视频列表，视频列表包含收藏夹中的
 */
export function FavoriteVideo(count: number, cursor: number): $CancellablePromise<model$0.FavoriteVideoResponse> {
    return $Call.ByID(152409887, count, cursor);
}

/**
 * FavoritesVideoList 获取指定收藏夹中的视频列表。
 * 收藏夹 ID 可能超过 JS 安全整数范围，前端应传 collects_id_str，避免 Wails number 精度丢失。
 */
export function FavoritesVideoList(collectIDStr: string, cursor: number, count: number): $CancellablePromise<model$0.FavoriteVideoResponse> {
    return $Call.ByID(1560645572, collectIDStr, cursor, count);
}

/**
 * FollowList 关注列表，需要分页获取，前端默认20条。这里不再传参了，就默认20条了
 */
export function FollowList(offset: number): $CancellablePromise<model$0.FollowResponse> {
    return $Call.ByID(2226717041, offset);
}

/**
 * GetCookie 获取Cookie
 */
export function GetCookie(): $CancellablePromise<string> {
    return $Call.ByID(2386691794);
}

/**
 * History 观看历史接口，获取用户观看过的视频列表
 * maxCursor参数是分页的游标
 * status: 用于过滤历史记录的状态，取值范围："-1" 表示不限制，"1" 表示已看完，"0" 表示未看完
 * category: 用于过滤历史记录的分类，0：不限制，1：二次元，2：音乐，3：体育，4：电影，5：游戏
 * directory: 用于过滤历史记录的时长，0：不限制，1：小于1分钟，2：1-3分钟，3：3-10分钟，4：10分钟以上
 */
export function History(maxCursor: number, status: number, category: number, directory: number): $CancellablePromise<model$0.HistoryResponse> {
    return $Call.ByID(1977065888, maxCursor, status, category, directory);
}

/**
 * ParseSecUserID 从用户空间URL或分享链接中提取sec_user_id
 */
export function ParseSecUserID(URLOrSecUserID: string): $CancellablePromise<string> {
    return $Call.ByID(3833826710, URLOrSecUserID);
}

/**
 * ParseVideo 解析抖音视频链接，返回awemeID，为保证整体工作流，精选链接只返回awemeID，然后前端再次根据awemeID请求视频详情接口获取视频详情
 */
export function ParseVideo(link: string): $CancellablePromise<string> {
    return $Call.ByID(3312623754, link);
}

/**
 * Profile 个人信息接口
 */
export function Profile(): $CancellablePromise<model$0.MyInfoResponse> {
    return $Call.ByID(564887389);
}

export function PublicHeaders(): $CancellablePromise<any> {
    return $Call.ByID(2739440541);
}

/**
 * SearchFollow 通过昵称或抖音号搜索关注列表，返回的结果不一定是关注列表中的用户，需要二次过滤
 */
export function SearchFollow(keyword: string): $CancellablePromise<model$0.SearchFollowResponse[] | null> {
    return $Call.ByID(1850755105, keyword);
}

export function SetCookie(cookie: string): $CancellablePromise<void> {
    return $Call.ByID(3631547550, cookie);
}

/**
 * User 获取用户信息
 */
export function User(secUserId: string): $CancellablePromise<model$0.UserResponse> {
    return $Call.ByID(1003674299, secUserId);
}

/**
 * UserSeries 用户空间的合集列表
 */
export function UserSeries(secUserID: string, cursor: number, count: number): $CancellablePromise<model$0.UserSeriesResponse> {
    return $Call.ByID(1756815186, secUserID, cursor, count);
}

/**
 * UserVideoList 用户空间的视频列表
 */
export function UserVideoList(secUserId: string, count: number, maxCursor: number): $CancellablePromise<model$0.UserVideoListResponse> {
    return $Call.ByID(4248514578, secUserId, count, maxCursor);
}

/**
 * VideoDetail 获取视频详情
 */
export function VideoDetail(awemeID: string): $CancellablePromise<model$0.AwemeItem> {
    return $Call.ByID(3307467386, awemeID);
}
