// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DouyinDownloadAsset {
    "url": string;
    "kind": string;
    "ext": string;
}

export interface DouyinDownloadBatchResult {
    "results": DouyinDownloadResult[] | null;
    "success": number;
    "failed": number;
}

export interface DouyinDownloadHistoryItem {
    "awemeId": string;
    "title": string;
    "cover": string;
    "duration": number;
    "authorName": string;
    "publishTime": number;
    "diggCount": number;
    "collectCount": number;
    "sourceName": string;
    "sourceKind": string;
    "path": string;
    "isImageAlbum": boolean;
    "imageCount": number;
    "downloadKind": string;

    /**
     * Wails 绑定生成不支持直接暴露 time.Time，保存为 RFC3339 字符串给前端解析。
     */
    "downloaded": string;
}

export interface DouyinDownloadResult {
    "awemeId": string;
    "title": string;
    "path": string;
    "error": string;
}

/**
 * DouyinDownloadTask 是前端提交给后端的最小任务协议。
 * 前端已经完成清晰度选择，所以后端只消费最终 videoURL；图片合集则使用 ImageURLs。
 */
export interface DouyinDownloadTask {
    "awemeId": string;
    "sourceKind": string;
    "sourceName": string;
    "title": string;
    "cover": string;
    "duration": number;
    "authorName": string;
    "publishTime": number;
    "diggCount": number;
    "collectCount": number;
    "videoURL": string;
    "imageURLs": string[] | null;
    "assets": DouyinDownloadAsset[] | null;
    "musicURL": string;
}
