/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DouyinRouteImport } from './routes/douyin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BilibiliRouteRouteImport } from './routes/bilibili/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as BilibiliIndexRouteImport } from './routes/bilibili/index'
import { Route as BilibiliProfileRouteImport } from './routes/bilibili/profile'
import { Route as BilibiliHistoryRouteImport } from './routes/bilibili/history'
import { Route as BilibiliFavoriteRouteImport } from './routes/bilibili/favorite'
import { Route as BilibiliDownloadRouteImport } from './routes/bilibili/download'
import { Route as BilibiliUpRouteRouteImport } from './routes/bilibili/up/route'
import { Route as BilibiliUpIndexRouteImport } from './routes/bilibili/up/index'
import { Route as BilibiliUpMidRouteImport } from './routes/bilibili/up/$mid'

const DouyinRoute = DouyinRouteImport.update({
  id: '/douyin',
  path: '/douyin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliRouteRoute = BilibiliRouteRouteImport.update({
  id: '/bilibili',
  path: '/bilibili',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliIndexRoute = BilibiliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliProfileRoute = BilibiliProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliHistoryRoute = BilibiliHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliFavoriteRoute = BilibiliFavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliDownloadRoute = BilibiliDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliUpRouteRoute = BilibiliUpRouteRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliUpIndexRoute = BilibiliUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BilibiliUpRouteRoute,
} as any)
const BilibiliUpMidRoute = BilibiliUpMidRouteImport.update({
  id: '/$mid',
  path: '/$mid',
  getParentRoute: () => BilibiliUpRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/douyin': typeof DouyinRoute
  '/bilibili/up': typeof BilibiliUpRouteRouteWithChildren
  '/bilibili/download': typeof BilibiliDownloadRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/bilibili/': typeof BilibiliIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bilibili/up/$mid': typeof BilibiliUpMidRoute
  '/bilibili/up/': typeof BilibiliUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/douyin': typeof DouyinRoute
  '/bilibili/download': typeof BilibiliDownloadRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/bilibili': typeof BilibiliIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/bilibili/up/$mid': typeof BilibiliUpMidRoute
  '/bilibili/up': typeof BilibiliUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/douyin': typeof DouyinRoute
  '/bilibili/up': typeof BilibiliUpRouteRouteWithChildren
  '/bilibili/download': typeof BilibiliDownloadRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/bilibili/': typeof BilibiliIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bilibili/up/$mid': typeof BilibiliUpMidRoute
  '/bilibili/up/': typeof BilibiliUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bilibili'
    | '/about'
    | '/douyin'
    | '/bilibili/up'
    | '/bilibili/download'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/bilibili/'
    | '/settings/'
    | '/bilibili/up/$mid'
    | '/bilibili/up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/douyin'
    | '/bilibili/download'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/bilibili'
    | '/settings'
    | '/bilibili/up/$mid'
    | '/bilibili/up'
  id:
    | '__root__'
    | '/'
    | '/bilibili'
    | '/about'
    | '/douyin'
    | '/bilibili/up'
    | '/bilibili/download'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/bilibili/'
    | '/settings/'
    | '/bilibili/up/$mid'
    | '/bilibili/up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilibiliRouteRoute: typeof BilibiliRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DouyinRoute: typeof DouyinRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/douyin': {
      id: '/douyin'
      path: '/douyin'
      fullPath: '/douyin'
      preLoaderRoute: typeof DouyinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili': {
      id: '/bilibili'
      path: '/bilibili'
      fullPath: '/bilibili'
      preLoaderRoute: typeof BilibiliRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili/': {
      id: '/bilibili/'
      path: '/'
      fullPath: '/bilibili/'
      preLoaderRoute: typeof BilibiliIndexRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/profile': {
      id: '/bilibili/profile'
      path: '/profile'
      fullPath: '/bilibili/profile'
      preLoaderRoute: typeof BilibiliProfileRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/history': {
      id: '/bilibili/history'
      path: '/history'
      fullPath: '/bilibili/history'
      preLoaderRoute: typeof BilibiliHistoryRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/favorite': {
      id: '/bilibili/favorite'
      path: '/favorite'
      fullPath: '/bilibili/favorite'
      preLoaderRoute: typeof BilibiliFavoriteRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/download': {
      id: '/bilibili/download'
      path: '/download'
      fullPath: '/bilibili/download'
      preLoaderRoute: typeof BilibiliDownloadRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/up': {
      id: '/bilibili/up'
      path: '/up'
      fullPath: '/bilibili/up'
      preLoaderRoute: typeof BilibiliUpRouteRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/up/': {
      id: '/bilibili/up/'
      path: '/'
      fullPath: '/bilibili/up/'
      preLoaderRoute: typeof BilibiliUpIndexRouteImport
      parentRoute: typeof BilibiliUpRouteRoute
    }
    '/bilibili/up/$mid': {
      id: '/bilibili/up/$mid'
      path: '/$mid'
      fullPath: '/bilibili/up/$mid'
      preLoaderRoute: typeof BilibiliUpMidRouteImport
      parentRoute: typeof BilibiliUpRouteRoute
    }
  }
}

interface BilibiliUpRouteRouteChildren {
  BilibiliUpMidRoute: typeof BilibiliUpMidRoute
  BilibiliUpIndexRoute: typeof BilibiliUpIndexRoute
}

const BilibiliUpRouteRouteChildren: BilibiliUpRouteRouteChildren = {
  BilibiliUpMidRoute: BilibiliUpMidRoute,
  BilibiliUpIndexRoute: BilibiliUpIndexRoute,
}

const BilibiliUpRouteRouteWithChildren = BilibiliUpRouteRoute._addFileChildren(
  BilibiliUpRouteRouteChildren,
)

interface BilibiliRouteRouteChildren {
  BilibiliUpRouteRoute: typeof BilibiliUpRouteRouteWithChildren
  BilibiliDownloadRoute: typeof BilibiliDownloadRoute
  BilibiliFavoriteRoute: typeof BilibiliFavoriteRoute
  BilibiliHistoryRoute: typeof BilibiliHistoryRoute
  BilibiliProfileRoute: typeof BilibiliProfileRoute
  BilibiliIndexRoute: typeof BilibiliIndexRoute
}

const BilibiliRouteRouteChildren: BilibiliRouteRouteChildren = {
  BilibiliUpRouteRoute: BilibiliUpRouteRouteWithChildren,
  BilibiliDownloadRoute: BilibiliDownloadRoute,
  BilibiliFavoriteRoute: BilibiliFavoriteRoute,
  BilibiliHistoryRoute: BilibiliHistoryRoute,
  BilibiliProfileRoute: BilibiliProfileRoute,
  BilibiliIndexRoute: BilibiliIndexRoute,
}

const BilibiliRouteRouteWithChildren = BilibiliRouteRoute._addFileChildren(
  BilibiliRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilibiliRouteRoute: BilibiliRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DouyinRoute: DouyinRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
