/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DouyinRouteImport } from './routes/douyin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BilibiliRouteRouteImport } from './routes/bilibili/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as BilibiliIndexRouteImport } from './routes/bilibili/index'
import { Route as BilibiliUpRouteImport } from './routes/bilibili/up'
import { Route as BilibiliSingleRouteImport } from './routes/bilibili/single'
import { Route as BilibiliSeriesRouteImport } from './routes/bilibili/series'
import { Route as BilibiliProfileRouteImport } from './routes/bilibili/profile'
import { Route as BilibiliHistoryRouteImport } from './routes/bilibili/history'
import { Route as BilibiliFavoriteRouteImport } from './routes/bilibili/favorite'

const DouyinRoute = DouyinRouteImport.update({
  id: '/douyin',
  path: '/douyin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliRouteRoute = BilibiliRouteRouteImport.update({
  id: '/bilibili',
  path: '/bilibili',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliIndexRoute = BilibiliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliUpRoute = BilibiliUpRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliSingleRoute = BilibiliSingleRouteImport.update({
  id: '/single',
  path: '/single',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliSeriesRoute = BilibiliSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliProfileRoute = BilibiliProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliHistoryRoute = BilibiliHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliFavoriteRoute = BilibiliFavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => BilibiliRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/douyin': typeof DouyinRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/bilibili/series': typeof BilibiliSeriesRoute
  '/bilibili/single': typeof BilibiliSingleRoute
  '/bilibili/up': typeof BilibiliUpRoute
  '/bilibili/': typeof BilibiliIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/douyin': typeof DouyinRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/bilibili/series': typeof BilibiliSeriesRoute
  '/bilibili/single': typeof BilibiliSingleRoute
  '/bilibili/up': typeof BilibiliUpRoute
  '/bilibili': typeof BilibiliIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/douyin': typeof DouyinRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/bilibili/series': typeof BilibiliSeriesRoute
  '/bilibili/single': typeof BilibiliSingleRoute
  '/bilibili/up': typeof BilibiliUpRoute
  '/bilibili/': typeof BilibiliIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bilibili'
    | '/about'
    | '/douyin'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/bilibili/series'
    | '/bilibili/single'
    | '/bilibili/up'
    | '/bilibili/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/douyin'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/bilibili/series'
    | '/bilibili/single'
    | '/bilibili/up'
    | '/bilibili'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/bilibili'
    | '/about'
    | '/douyin'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/bilibili/series'
    | '/bilibili/single'
    | '/bilibili/up'
    | '/bilibili/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilibiliRouteRoute: typeof BilibiliRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DouyinRoute: typeof DouyinRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/douyin': {
      id: '/douyin'
      path: '/douyin'
      fullPath: '/douyin'
      preLoaderRoute: typeof DouyinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili': {
      id: '/bilibili'
      path: '/bilibili'
      fullPath: '/bilibili'
      preLoaderRoute: typeof BilibiliRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili/': {
      id: '/bilibili/'
      path: '/'
      fullPath: '/bilibili/'
      preLoaderRoute: typeof BilibiliIndexRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/up': {
      id: '/bilibili/up'
      path: '/up'
      fullPath: '/bilibili/up'
      preLoaderRoute: typeof BilibiliUpRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/single': {
      id: '/bilibili/single'
      path: '/single'
      fullPath: '/bilibili/single'
      preLoaderRoute: typeof BilibiliSingleRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/series': {
      id: '/bilibili/series'
      path: '/series'
      fullPath: '/bilibili/series'
      preLoaderRoute: typeof BilibiliSeriesRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/profile': {
      id: '/bilibili/profile'
      path: '/profile'
      fullPath: '/bilibili/profile'
      preLoaderRoute: typeof BilibiliProfileRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/history': {
      id: '/bilibili/history'
      path: '/history'
      fullPath: '/bilibili/history'
      preLoaderRoute: typeof BilibiliHistoryRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/favorite': {
      id: '/bilibili/favorite'
      path: '/favorite'
      fullPath: '/bilibili/favorite'
      preLoaderRoute: typeof BilibiliFavoriteRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
  }
}

interface BilibiliRouteRouteChildren {
  BilibiliFavoriteRoute: typeof BilibiliFavoriteRoute
  BilibiliHistoryRoute: typeof BilibiliHistoryRoute
  BilibiliProfileRoute: typeof BilibiliProfileRoute
  BilibiliSeriesRoute: typeof BilibiliSeriesRoute
  BilibiliSingleRoute: typeof BilibiliSingleRoute
  BilibiliUpRoute: typeof BilibiliUpRoute
  BilibiliIndexRoute: typeof BilibiliIndexRoute
}

const BilibiliRouteRouteChildren: BilibiliRouteRouteChildren = {
  BilibiliFavoriteRoute: BilibiliFavoriteRoute,
  BilibiliHistoryRoute: BilibiliHistoryRoute,
  BilibiliProfileRoute: BilibiliProfileRoute,
  BilibiliSeriesRoute: BilibiliSeriesRoute,
  BilibiliSingleRoute: BilibiliSingleRoute,
  BilibiliUpRoute: BilibiliUpRoute,
  BilibiliIndexRoute: BilibiliIndexRoute,
}

const BilibiliRouteRouteWithChildren = BilibiliRouteRoute._addFileChildren(
  BilibiliRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilibiliRouteRoute: BilibiliRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DouyinRoute: DouyinRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
