// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStorage() {
  return window['go']['utils']['Settings']['GetStorage']();
}

export function GetTheme() {
  return window['go']['utils']['Settings']['GetTheme']();
}

export function SetStorage(arg1) {
  return window['go']['utils']['Settings']['SetStorage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['utils']['Settings']['SetTheme'](arg1);
}
