// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Collection(arg1:number,arg2:number):Promise<model.CollectionData>;

export function CollectionItem(arg1:string,arg2:number,arg3:number):Promise<model.CollectionItemData>;

export function Favorites(arg1:number,arg2:number,arg3:number):Promise<model.FavoriteData>;

export function FavoritesList():Promise<model.FavoritesData>;

export function FollowList(arg1:number,arg2:number):Promise<model.FollowData>;

export function IsLoggedIn():Promise<boolean>;

export function LogOut():Promise<model.LogOut>;

export function MyInfo():Promise<model.MyInfoProfile>;

export function PollQRCode(arg1:string):Promise<model.PollQRCodeData>;

export function QRCode():Promise<model.QRCodeData>;

export function Refresh():Promise<model.RefreshData>;

export function SeasonsSeriesList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<model.SeasonsSeriesData>;
