// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Collection(arg1, arg2) {
  return window['go']['api']['BiliBili']['Collection'](arg1, arg2);
}

export function CollectionItem(arg1, arg2, arg3) {
  return window['go']['api']['BiliBili']['CollectionItem'](arg1, arg2, arg3);
}

export function Favorites(arg1, arg2, arg3) {
  return window['go']['api']['BiliBili']['Favorites'](arg1, arg2, arg3);
}

export function FavoritesList() {
  return window['go']['api']['BiliBili']['FavoritesList']();
}

export function FollowList(arg1, arg2) {
  return window['go']['api']['BiliBili']['FollowList'](arg1, arg2);
}

export function IsLoggedIn() {
  return window['go']['api']['BiliBili']['IsLoggedIn']();
}

export function LogOut() {
  return window['go']['api']['BiliBili']['LogOut']();
}

export function MyInfo() {
  return window['go']['api']['BiliBili']['MyInfo']();
}

export function PollQRCode(arg1) {
  return window['go']['api']['BiliBili']['PollQRCode'](arg1);
}

export function QRCode() {
  return window['go']['api']['BiliBili']['QRCode']();
}

export function Refresh() {
  return window['go']['api']['BiliBili']['Refresh']();
}

export function SeasonsSeriesList(arg1, arg2, arg3, arg4) {
  return window['go']['api']['BiliBili']['SeasonsSeriesList'](arg1, arg2, arg3, arg4);
}
