// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function FavoritesList():Promise<model.FavoritesData>;

export function IsLoggedIn():Promise<boolean>;

export function LogOut():Promise<model.LogOut>;

export function MyInfo():Promise<model.MyInfoProfile>;

export function PollQRCode(arg1:string):Promise<model.PollQRCodeData>;

export function QRCode():Promise<model.QRCodeData>;

export function Refresh():Promise<model.RefreshData>;
