// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function FollowList():Promise<model.Follow>;

export function Profile():Promise<model.MyInfo>;

export function User(arg1:string):Promise<model.UserData>;
