// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FollowList() {
  return window['go']['api']['Douyin']['FollowList']();
}

export function Profile() {
  return window['go']['api']['Douyin']['Profile']();
}

export function User(arg1) {
  return window['go']['api']['Douyin']['User'](arg1);
}
