// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectList(arg1) {
  return window['go']['api']['Douyin']['CollectList'](arg1);
}

export function FavoriteVideo(arg1, arg2) {
  return window['go']['api']['Douyin']['FavoriteVideo'](arg1, arg2);
}

export function FollowList(arg1) {
  return window['go']['api']['Douyin']['FollowList'](arg1);
}

export function GetCookie() {
  return window['go']['api']['Douyin']['GetCookie']();
}

export function Profile() {
  return window['go']['api']['Douyin']['Profile']();
}

export function SetCookie(arg1) {
  return window['go']['api']['Douyin']['SetCookie'](arg1);
}

export function User(arg1) {
  return window['go']['api']['Douyin']['User'](arg1);
}
