// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CollectList(arg1:number):Promise<model.CollectListResponse>;

export function FavoriteVideo(arg1:number,arg2:number):Promise<model.FavoriteVideoResponse>;

export function FollowList(arg1:number):Promise<model.FollowResponse>;

export function GetCookie():Promise<string>;

export function Profile():Promise<model.MyInfo>;

export function SetCookie(arg1:string):Promise<void>;

export function User(arg1:string):Promise<model.UserData>;
